# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1suT-BkwimFDgh-JLb7yv5OMEzD9_yMTq
"""

# Importando as bibliotecas necessárias
from molmass import Formula
import streamlit as st
from PIL import Image

# Inserindo os parâmetros físico-químicos do produto
pureza_FeCl3 = 0.9
densidade_FeCl3 = 1.39 #kg/L
concentracao_FeCl3 = 0.38 #kg/kg
p = Formula('P')
p = p.mass
fe = Formula('Fe')
fe = fe.mass
feCl3 = Formula('FeCl3')
feCl3 = feCl3.mass
concentracao_NaClO = 13 #g Cloro ativo/100mL
concentracao_C2H4O3 = 0.15 #kg/kg
densidade_C2H4O3 = 1.12 #kg/L

# Criando objeto do Streamlit:

def main():

    st.sidebar.info("Dosagem Química ETE's")
    
    image = Image.open('ETE.jpg')
    
    st.sidebar.image(image)
    
    pagina = st.sidebar.selectbox('Selecione a página desejada', ['Cloreto Férrico', 'Hipoclorito de Sódio', 
                                                                  'Ácido Peracético'])
    
    if pagina == 'Cloreto Férrico':
        
        st.title('Sistema de dosagem de Cloreto Férrico')
        
        p_afluente = st.number_input('Fósforo afluente (mg/L)', min_value = 0, max_value = 30, value = 7)
        
        p_efluente = st.number_input('Fósforo efluente (mg/L)', min_value = 0, max_value = 10, value = 3)
        
        mols_Fe_P = st.slider('Relação molar Fe/P', min_value = 0, max_value = 4, value = 2)
        
        vazao_vol_ETE = st.number_input('Vazão volumétrica ETE (L/s)', min_value = 1, max_value = 5000, value = 1)
        
        quantidade_modulos = st.selectbox('Número de módulos de tratamento', (1, 2, 3, 4, 5))
                                          
        horas_funcionamento = st.number_input('Tempo de funcionamento da ETE (h/dia)', min_value = 0, max_value = 24, value = 0)
        
        dias_estocagem = st.slider('Tempo de armazenamento (dias)', min_value = 0, max_value = 60, value = 0)

        p_ent = float(p_afluente)
        p_saida = float(p_efluente)
        relacao_molar = float(mols_Fe_P)
        vazao_ETE = float(vazao_vol_ETE)
        numero_modulos = int(quantidade_modulos)
        tempo_operacao = float(horas_funcionamento)
        tempo_estocagem = float(dias_estocagem)

        vazao_bomba_ClFe3 = (relacao_molar * (fe / p) * (p_ent - p_saida) * vazao_ETE * 3600) / (densidade_FeCl3 * concentracao_FeCl3 * (fe / feCl3) * 10**6)
        vazao_bomba_arredondada_ClFe3 = str(round(vazao_bomba_ClFe3))
        
        faixa_superior_bomba = str(round(2 * (relacao_molar * (fe / p) * (p_ent - p_saida) * vazao_ETE * 3600) / (densidade_FeCl3 * concentracao_FeCl3 * (fe / feCl3) * 10**6)))
        
        faixa_recomendada = [0 , int(faixa_superior_bomba)]
        
        dosagem_FeCl3 = (vazao_bomba_ClFe3 * densidade_FeCl3 * concentracao_FeCl3 * (1000 / 3600)) / (vazao_ETE / 1000)
        dosagem_FeCl3_arredondada = str(round(dosagem_FeCl3, 2))

        estocagem_FeCl3 = (numero_modulos * vazao_bomba_ClFe3 * tempo_operacao * tempo_estocagem) / 1000
        estocagem_FeCl3_arredondada = str(round(estocagem_FeCl3, 0))
        
        
        st.info(f'\nVazão nominal de cada bomba dosadora --> {vazao_bomba_arredondada_ClFe3} L/h.módulo')
        
        st.info(f'\nFaixa recomendada bomba dosadora --> {faixa_recomendada} L/h.módulo')
        
        st.info(f'\nDosagem correspondente por módulo --> {dosagem_FeCl3_arredondada} mg/L')
        
        st.info(f'\nVolume mínimo recomendado de armazenamento --> {estocagem_FeCl3_arredondada} m³')
        
        
    if pagina == 'Hipoclorito de Sódio':
        
        st.title('Sistema de dosagem de Hipoclorito de Sódio')
                 
        dosagem = st.number_input('Dosagem (mg/L)', min_value = 0, max_value = 50, value = 5)
    
        vazao_vol_ETE = st.number_input('Vazão volumétrica ETE (L/s)', min_value = 1, max_value = 5000, value = 1)
        
        quantidade_modulos = st.selectbox('Número de módulos de tratamento', (1, 2, 3, 4, 5))
        
        horas_funcionamento = st.number_input('Tempo de funcionamento da ETE (h/dia)', min_value = 0, max_value = 24, value = 0)
        
        dias_estocagem = st.slider('Tempo de armazenamento (dias)', min_value = 0, max_value = 60, value = 0)

        dosag = float(dosagem)
        vazao_ETE = float(vazao_vol_ETE)
        numero_modulos = int(quantidade_modulos)
        tempo_operacao = float(horas_funcionamento)
        tempo_estocagem = float(dias_estocagem)
        
        vazao_bomba_NaClO = (dosag * 100 * vazao_ETE * 3600) / (10 ** 6 * concentracao_NaClO)
        vazao_bomba_arredondada_NaClO = str(round(vazao_bomba_NaClO))
        
        faixa_superior_bomba = str(round(2 * (dosag * 100 * vazao_ETE * 3600) / (10 ** 6 * concentracao_NaClO)))
        
        faixa_recomendada = [0 , int(faixa_superior_bomba)]

        estocagem_NaClO = (numero_modulos * vazao_bomba_NaClO * tempo_operacao * tempo_estocagem) / 1000
        estocagem_NaClO_arredondada = str(round(estocagem_NaClO, 0))
        
        
        st.info(f'\nVazão nominal de cada bomba dosadora --> {vazao_bomba_arredondada_NaClO} L/h.módulo')
        
        st.info(f'\nFaixa recomendada bomba dosadora --> {faixa_recomendada} L/h.módulo')
        
        st.info(f'\nVolume mínimo recomendado de armazenamento --> {estocagem_NaClO_arredondada} m³')
        
        
    if pagina == 'Ácido Peracético':
        
        st.title('Sistema de dosagem de Ácido Peracético')

        dosagem = st.number_input('Dosagem (mg/L)', min_value = 0, max_value = 50, value = 5)
    
        vazao_vol_ETE = st.number_input('Vazão volumétrica ETE (L/s)', min_value = 1, max_value = 5000, value = 1)
        
        quantidade_modulos = st.selectbox('Número de módulos de tratamento', (1, 2, 3, 4, 5))
        
        horas_funcionamento = st.number_input('Tempo de funcionamento da ETE (h/dia)', min_value = 0, max_value = 24, value = 0)
        
        dias_estocagem = st.slider('Tempo de armazenamento (dias)', min_value = 0, max_value = 60, value = 0)
        
        dosag = float(dosagem)
        vazao_ETE = float(vazao_vol_ETE)
        numero_modulos = int(quantidade_modulos)
        tempo_operacao = float(horas_funcionamento)
        tempo_estocagem = float(dias_estocagem)
        
        vazao_bomba_C2H4O3 = (dosag * vazao_ETE * 3600) / (10 ** 6 * concentracao_C2H4O3 * densidade_C2H4O3)
        vazao_bomba_arredondada_C2H4O3 = str(round(vazao_bomba_C2H4O3))
        
        faixa_superior_bomba = str(round(2 * (dosag * vazao_ETE * 3600) / (10 ** 6 * concentracao_C2H4O3 * densidade_C2H4O3)))
        
        faixa_recomendada = [0 , int(faixa_superior_bomba)]

        estocagem_C2H4O3 = (numero_modulos * vazao_bomba_C2H4O3 * tempo_operacao * tempo_estocagem) / 1000
        estocagem_C2H4O3_arredondada = str(round(estocagem_C2H4O3, 0))

        st.info(f'\nVazão nominal de cada bomba dosadora --> {vazao_bomba_arredondada_C2H4O3} L/h.módulo')
        
        st.info(f'\nFaixa recomendada bomba dosadora --> {faixa_recomendada} L/h.módulo')
        
        st.info(f'\nVolume mínimo recomendado de armazenamento --> {estocagem_C2H4O3_arredondada} m³')
        
        
if __name__ == '__main__':
    
    main()

